[package]
name = "urldebloater"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.35", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
arboard = "3.3.0"
anyhow = "1.0"
urlwasher = { path = "../urlwasher" }
